### ISSUE TITLE
Display oldest date loaded

### ISSUE THREAD

**Issue by c-harding** [benfoxall/lastfm-to-csv#29]
Hi @benfoxall, I would find it very useful to show the oldest date loaded as part of the partial loading indicator, as well as the page count. Would you accept a pull request to this effect? E.g. “Fetching page 3/100 (20 Feb 2024)” rather than just “Fetching page 3/100”

**Comment by benfoxall** [comment]
Hey @c-harding, good suggestion.

I just implemented this in 78c4d56f4a3b1b280dff6176e63be0d2436187ea – apologies I didn't properly read your offer of a PR (I'd gladly accept one if there's anything else you'd want to change).

![image](https://github.com/benfoxall/lastfm-to-csv/assets/51385/0b239bb4-d3dd-4db1-89d8-fa1cedcf313b)

**Comment by c-harding** [comment]
That was quick, thank you very much!
